trigger: none

pool:
  name: Cloud2.0
steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
  displayName: 'Terraform : init'
  inputs:
    provider: aws
    workingDirectory: Composite
    commandOptions: '-reconfigure'
    backendServiceAWS: 'AFT-DEV'
    backendAWSBucketName: 'kmbl-terraform-state-s3-bucket'
    backendAWSKey: 'devopssupplychain-01396/supplychain-devops-01396-ado_ec2/nonprod/supplychain-01396-devops-ado_ec2-nonprod.tfstate'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
  displayName: 'Terraform : validate'
  inputs:
    provider: aws
    command: validate
    workingDirectory: Composite
    backendServiceAWS: 'AFT-DEV'
    backendAWSBucketName: 'kmbl-terraform-state-s3-bucket'
    backendAWSKey: 'devopssupplychain-01396/supplychain-devops-01396-s3/nonprod/supplychain-01396-devops-s3-nonprod.tfstate'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
  displayName: 'Terraform : plan'
  inputs:
    provider: aws
    command: plan
    workingDirectory: Composite
    commandOptions: '-var-file=global.tfvars'
    environmentServiceNameAWS: 'AFT-DEV'
    backendServiceAWS: 'AFT-DEV'
    backendAWSBucketName: 'kmbl-terraform-state-s3-bucket'
    backendAWSKey: 'devopssupplychain-01396/supplychain-devops-01396-s3/nonprod/supplychain-01396-devops-s3-nonprod.tfstate'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
  displayName: 'Terraform : Apply'
  inputs:
    provider: aws
    command: apply
    workingDirectory: Composite
    commandOptions: '-var-file=global.tfvars'
    environmentServiceNameAWS: 'AFT-DEV'
    backendServiceAWS: 'AFT-DEV'
    backendAWSBucketName: 'kmbl-terraform-state-s3-bucket'
    backendAWSKey: 'devopssupplychain-01396/supplychain-devops-01396-s3/nonprod/supplychain-01396-devops-s3-nonprod.tfstate'
